//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSOAp.ServiciosWebSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sv/", ConfigurationName="ServiciosWebSOAP.Servicios")]
    public interface Servicios {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://sv/)
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/Servicios/ProcesarPagoRequest", ReplyAction="http://sv/Servicios/ProcesarPagoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSOAp.ServiciosWebSOAP.ProcesarPagoResponse ProcesarPago(ClienteSOAp.ServiciosWebSOAP.ProcesarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/Servicios/ProcesarPagoRequest", ReplyAction="http://sv/Servicios/ProcesarPagoResponse")]
        System.Threading.Tasks.Task<ClienteSOAp.ServiciosWebSOAP.ProcesarPagoResponse> ProcesarPagoAsync(ClienteSOAp.ServiciosWebSOAP.ProcesarPagoRequest request);
        
        // CODEGEN: Generating message contract since element name password from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/Servicios/LoginRequest", ReplyAction="http://sv/Servicios/LoginResponse")]
        ClienteSOAp.ServiciosWebSOAP.LoginResponse Login(ClienteSOAp.ServiciosWebSOAP.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sv/Servicios/LoginRequest", ReplyAction="http://sv/Servicios/LoginResponse")]
        System.Threading.Tasks.Task<ClienteSOAp.ServiciosWebSOAP.LoginResponse> LoginAsync(ClienteSOAp.ServiciosWebSOAP.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarPago", WrapperNamespace="http://sv/", IsWrapped=true)]
    public partial class ProcesarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int total;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int pago;
        
        public ProcesarPagoRequest() {
        }
        
        public ProcesarPagoRequest(int total, int pago) {
            this.total = total;
            this.pago = pago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarPagoResponse", WrapperNamespace="http://sv/", IsWrapped=true)]
    public partial class ProcesarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public ProcesarPagoResponse() {
        }
        
        public ProcesarPagoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://sv/", Order=0)]
        public ClienteSOAp.ServiciosWebSOAP.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ClienteSOAp.ServiciosWebSOAP.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string password, string username) {
            this.password = password;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://sv/", Order=0)]
        public ClienteSOAp.ServiciosWebSOAP.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ClienteSOAp.ServiciosWebSOAP.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosChannel : ClienteSOAp.ServiciosWebSOAP.Servicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosClient : System.ServiceModel.ClientBase<ClienteSOAp.ServiciosWebSOAP.Servicios>, ClienteSOAp.ServiciosWebSOAP.Servicios {
        
        public ServiciosClient() {
        }
        
        public ServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAp.ServiciosWebSOAP.ProcesarPagoResponse ClienteSOAp.ServiciosWebSOAP.Servicios.ProcesarPago(ClienteSOAp.ServiciosWebSOAP.ProcesarPagoRequest request) {
            return base.Channel.ProcesarPago(request);
        }
        
        public int ProcesarPago(int total, int pago) {
            ClienteSOAp.ServiciosWebSOAP.ProcesarPagoRequest inValue = new ClienteSOAp.ServiciosWebSOAP.ProcesarPagoRequest();
            inValue.total = total;
            inValue.pago = pago;
            ClienteSOAp.ServiciosWebSOAP.ProcesarPagoResponse retVal = ((ClienteSOAp.ServiciosWebSOAP.Servicios)(this)).ProcesarPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAp.ServiciosWebSOAP.ProcesarPagoResponse> ClienteSOAp.ServiciosWebSOAP.Servicios.ProcesarPagoAsync(ClienteSOAp.ServiciosWebSOAP.ProcesarPagoRequest request) {
            return base.Channel.ProcesarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAp.ServiciosWebSOAP.ProcesarPagoResponse> ProcesarPagoAsync(int total, int pago) {
            ClienteSOAp.ServiciosWebSOAP.ProcesarPagoRequest inValue = new ClienteSOAp.ServiciosWebSOAP.ProcesarPagoRequest();
            inValue.total = total;
            inValue.pago = pago;
            return ((ClienteSOAp.ServiciosWebSOAP.Servicios)(this)).ProcesarPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAp.ServiciosWebSOAP.LoginResponse ClienteSOAp.ServiciosWebSOAP.Servicios.Login(ClienteSOAp.ServiciosWebSOAP.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string password, string username) {
            ClienteSOAp.ServiciosWebSOAP.LoginRequest inValue = new ClienteSOAp.ServiciosWebSOAP.LoginRequest();
            inValue.Body = new ClienteSOAp.ServiciosWebSOAP.LoginRequestBody();
            inValue.Body.password = password;
            inValue.Body.username = username;
            ClienteSOAp.ServiciosWebSOAP.LoginResponse retVal = ((ClienteSOAp.ServiciosWebSOAP.Servicios)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAp.ServiciosWebSOAP.LoginResponse> ClienteSOAp.ServiciosWebSOAP.Servicios.LoginAsync(ClienteSOAp.ServiciosWebSOAP.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAp.ServiciosWebSOAP.LoginResponse> LoginAsync(string password, string username) {
            ClienteSOAp.ServiciosWebSOAP.LoginRequest inValue = new ClienteSOAp.ServiciosWebSOAP.LoginRequest();
            inValue.Body = new ClienteSOAp.ServiciosWebSOAP.LoginRequestBody();
            inValue.Body.password = password;
            inValue.Body.username = username;
            return ((ClienteSOAp.ServiciosWebSOAP.Servicios)(this)).LoginAsync(inValue);
        }
    }
}
